# config/meta.yml

meta_product_name: "Dish Advisor"
meta_title: "Dish Advisor - Review your Meal"
meta_description: "Review your meal so that friends can have a great experience."
meta_image: "brooke-lark-wMzx2nBdeng-unsplashcopy.jpg" # should exist in `app/assets/images/`
